language: scala
scala:
  - 2.11.1
sudo: false
cache:
  directories:
      - $HOME/.ivy2
addons:
  artifacts:
    upload-dir: travis-builds
    debug: true
    paths:
    - $(git ls-files -o | grep \.json$ | tr "\n" ":")
